### ISSUE TITLE
Sometimes valves are auto discovered twice

### ISSUE THREAD

**Issue by wjarka** [dbuezas/eq3btsmart#1]
It detected all of my valves, but one of them showed up twice. Let me know what I can provide to help you troubleshoot this (not sure if it's even worth troubleshooting, just wanted to report)

**Comment by dbuezas** [comment]
Thanks, I'll check the discovery code. I don't see that happening with mine

**Comment by dbuezas** [comment]
Is the second one discovered after you adding the first one? Or is the duplicate discovered while the first one was still not added?

**Comment by wjarka** [comment]
I installed the integration, went to devices and I already saw 5 thermostats instead of 4. Configured all of them and I still have that one stuck there ;)

**Comment by wjarka** [comment]
Thanks for creating this btw, seems to work as a charm ;)

**Comment by dbuezas** [comment]
Happy it worked for you too!
Don't doubt posting issues if you see something off :)

**Comment by wjarka** [comment]
Will do :)
