### ISSUE TITLE
Error message: Requirements for dbuezas_eq3btsmart not found: ['construct==2.10.56']

### ISSUE THREAD

**Issue by LXR85** [dbuezas/eq3btsmart#103]
After updating to 2024.1.5, I encounted this error message. Reboot, shutdown and power disconnect did not fix the issue. Here is the information from System Health:

## System Information

version | core-2024.1.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | armv7l
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4889
Installed Version | 1.34.0
Stage | running
Available Repositories | 1378
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.6 GB
disk_used | 25.8 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.7.0), Let's Encrypt (5.0.12), Terminal & SSH (9.8.1), ADB - Android Debug Bridge (0.7.0), Duck DNS (1.15.0), Spotify Connect (0.13.0), MPD (1.7.2), Mosquitto broker (6.4.0), Zigbee2MQTT (1.35.1-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 5
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 13, 2024 at 03:27
-- | --
current_recorder_run | January 23, 2024 at 11:30
estimated_db_size | 60.18 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by EuleMitKeule** [comment]
Can you open a terminal and do a `pip install construct==2.10.56` or reinstall the integration from HACS?

**Comment by LXR85** [comment]
A reinstall seems to have fixed it, at least 3 out of 5 thermostats. Thank you for your help!
