### ISSUE TITLE
How to work with the your eq3 services

### ISSUE THREAD

**Issue by FPMilan** [dbuezas/eq3btsmart#11]
You have the service eq3 fetch schedule, get serial and set schedule, how can I run the service and then see/disply the results? plus could you give an example also of how to set a new schedule?

_Originally posted by @FPMilan in https://github.com/dbuezas/eq3btsmart/issues/2#issuecomment-1310252214_

**Comment by dbuezas** [comment]
BTW, you can set it via the original library's API (or use the app) if you are in a hurry.

**Comment by dbuezas** [comment]
I personally use [this scheduler component](https://github.com/nielsfaber/scheduler-card) to set the temperature from HA

**Comment by FPMilan** [comment]
thank you for the input! can not test it right now unfortunately as my connection to the thermostats is again failing, I guess I first need a good Bluetooth USB-dongle first...

**Comment by dbuezas** [comment]
The Calor App I meant. Regarding pairing, I think it depends on the FW version, but you are right that you may have to re-pair
