### ISSUE TITLE
Connection with usb bt dongle

### ISSUE THREAD

**Issue by giga89** [dbuezas/eq3btsmart#12]
Logger: custom_components.dbuezas_eq3btsmart.climate
Source: custom_components/dbuezas_eq3btsmart/climate.py:369
Integration: dbuezas EQ3 Bluetooth Smart Thermostats
First occurred: 18:38:03 (89 occurrences)
Last logged: 22:18:06

[Termo_Cameretta] Error updating, will retry later: [org.bluez.Error.NotPermitted] Not paired
[Thermo_Cameretta] Error updating, will retry later: [org.bluez.Error.NotPermitted] Not paired
[Thermo_Cameretta] Error updating, will retry later: Thermo_Cameretta - 00:1A:22:16:F7:09 -> /org/bluez/hci1: Failed to connect: [org.bluez.Error.Failed] le-connection-abort-by-local: Interference/range; External Bluetooth adapter w/extension may help; Extension cables reduce USB 3 port interference
[Thermo_Cameretta] Error updating, will retry later: Thermo_Cameretta - 00:1A:22:16:F7:09 -> /org/bluez/hci1: Failed to connect:
[Thermo_Cameretta] Error updating, will retry later: Thermo_Cameretta - 00:1A:22:16:F7:09 -> /org/bluez/hci1: Failed to connect: failed to discover services, device disconnected

**Comment by dbuezas** [comment]
This usually means the thermostat is out of range.
You can confirm that by using bluethoothctl (see pairing in the readme)
Let me know if you succeed!
