### ISSUE TITLE
New devices discovered multiple times

### ISSUE THREAD

**Issue by paulokow** [dbuezas/eq3btsmart#14]
Hi,
I have the following issue. Some CC-RT-BLE devices which were discovered appear multiple times on the list.
There is no way to ignore them or get rid of them. I don't want to configure them, because they are actually connected via other HAs in my house.
![image](https://user-images.githubusercontent.com/31203062/202181380-17117696-38c9-4d00-9034-6c48c7864951.png)

See 00:1A:22:0B:6C:4B appears multiple times on the list.

**Comment by dbuezas** [comment]
Hi, thanks for taking the time to write this issue.

I honestly don't understand how this can happen, can you give me some more details? 
For example:
* Do you have multiple bluetooth adapters in the same machine?
* What does the ignore button do?
* Have you tried adding them and removing them?
* Do you have any esphome bluetooth proxies in that HA instance?
* ...

**Comment by markus1802** [comment]
HI,
a few days ago I started testing my eQ3-Devices with your integration and had the same issue. Some (not all) thermostats were shown twice. I configured one succesfulley and got the message "already configured" when configuring the second. The second tile then also disappeared.  Not sure, but probably I was still on version 1.*. I just have one HA in my house. Therefore I didn't need to ignore any of them. So this is not a big issue for me.

**Comment by dbuezas** [comment]
That has happened to me once. I assume it is a race condition in HA, where two discoveries come almost at the same time, and HA processes the second one before the first one is added to the known ones.

**Comment by paulokow** [comment]
@dbuezas 
> I honestly don't understand how this can happen, can you give me some more details? For example:
> 
> * Do you have multiple bluetooth adapters in the same machine?
No, just RPI3 built it adapter?

> * What does the ignore button do?
I don't see any ignore button. Where would I find it?

> * Have you tried adding them and removing them?
Not yet. Do you mean add and remove or add and disable?

> * Do you have any esphome bluetooth proxies in that HA instance?
No.

**Comment by dbuezas** [comment]
See #1 
There's the solution there too :)

**Comment by paulokow** [comment]
@dbuezas yes, there is sort of workaround to add the devices and then disable them. Now I have my entity registry polluted with those duplicated devices, which is not perfect.
I'm missing some option to ignore the devices without adding them. Maybe it's more a feature request.

**Comment by dbuezas** [comment]
I'm following the guidelines from HA to identify each device, so I think the duplication is a HA bug.

In any case, the workaround is not to disable the added entities, but:

1. Add them all so the duplicates disappear
2. Remove them all completely
3. Then ignore the discovery. Like this: 
<img width="371" alt="image" src="https://user-images.githubusercontent.com/777196/204237646-cef99783-06f2-4592-9169-c08f62db2a4b.png">
