### ISSUE TITLE
No communication with eq3 thermostat though device found

### ISSUE THREAD

**Issue by andrei-micu-ro** [dbuezas/eq3btsmart#2]
First of all thank you for the work on this integration.
I have successfully added the integration, though it takes a lot to find devices. I manually added a couple of them, while others were auto-discovered.
The problem is that they don't communicate with them.

![image](https://user-images.githubusercontent.com/73104962/196671465-c83f2504-d849-4429-bf52-fd942a057d9f.png)

HASS shows this error in the log:
"/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 505, in get_services
    raise BleakError("Not connected")

I've a Docker HASS on an Ubuntu distro with latest HASS version (2022.10.4).
bluetoothctl shows the devices and it seems it's receiving some data from them (be it only RSSI updates). A couple are already paired, others no (though pairing is not important for this as it's working on BLE).

Device 00:1A:22:16:C1:EF (public)
        Name: CC-RT-BLE
        Alias: CC-RT-BLE
        Paired: yes
        Trusted: yes
        Blocked: no
        Connected: no
        LegacyPairing: no
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Vendor specific           (3e135142-654f-9090-134a-a6ff5bb77046)
        UUID: Vendor specific           (9e5d1e47-5c13-43a0-8635-82ad38a1386f)
        ManufacturerData Key: 0x0000
        ManufacturerData Value:
  00 00 00 00 00 00 00 00 00                       .........
        ManufacturerData Key: 0x5201
        ManufacturerData Value:
  45 51 30 37 34 36 39 30 33                       EQ0746903
        RSSI: -87

I have to say that there's nothing wrong with the devices as on an older HASS instance (with BlueZ instead of Bleak) they work as expected.
Mentioning that I'm not multi-pairing the devices (only used an older Pi with older HASS to check, but now it's powered down).

I may have some misconfiguration on my Ubuntu as I had the older BlueZ setup and removing it makes the bluetoothctl go away.
Please advice and if you could share some extra details on your setup so I (we) can replicate accordingly.

**Comment by andrei-micu-ro** [comment]
Logger: homeassistant.helpers.entity
Source: components/bluetooth/models.py:291
First occurred: 1:10:53 AM (1 occurrences)
Last logged: 1:10:53 AM

Update for climate.living_thermostat fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 718, in async_device_update
    await task
  File "/config/custom_components/dbuezas_eq3btsmart/climate.py", line 388, in async_update
    await self._async_thermostat_update()
  File "/config/custom_components/dbuezas_eq3btsmart/climate.py", line 381, in _async_thermostat_update
    await self._thermostat.async_update()
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/eq3btsmart.py", line 239, in async_update
    await self._conn.async_make_request(PROP_WRITE_HANDLE, value)
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 111, in async_make_request
    raise ex
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 95, in async_make_request
    conn = await self.async_get_connection()
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 66, in async_get_connection
    await conn.connect(timeout=30)
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/models.py", line 291, in connect
    return await super().connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 392, in connect
    return await self._backend.connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 179, in connect
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Software caused connection abort

This is what I get initially and then the error I pasted above.
I tried removing the batteries from the valve, it indeed triggered HASS to re-add it, however same issue, no connectivity.
I'll play around with bluetoothctl to see what I receive from the valve and take it from there.
If you could tell me what's the expected result in CLI pls ?
Like a set of commands and what's the expected result so I can try to replicate locally.

The PC is a Ubuntu distro with HASS in Docker (started with dbus and everything, other BT devices work ok).
The only concern I have is that my Ubuntu may have older BT-related packages which may interfere... soooo let me know what should be installed and what not.

bluez:
  Installed: 5.53-0ubuntu3.6
- installed through "apt"

Name: bleak
Version: 0.19.0
- installed through "pip"

Thank you

**Comment by andrei-micu-ro** [comment]
Oh well, now it works :D
After some btmon and busctl monitor org.bluez saw that I only got RSSI updates from the thermostat which lead me to think that it's a problem with the pairing and no service data was coming through.
Unpaired it, restarted the service, re-paired it and now it works in HASS :)
And it works REALLY FAST !!!!! :)

So, all good, I'll do the same for the others.
Will close the issue.

**Comment by dbuezas** [comment]
Oh, it worked now, nice!

**Comment by FPMilan** [comment]
@andrei-micu-ro looks like I have exactly the same error. Can you share what exactly you did to resolve it - which service did you restart? So far repairing did not solve it for me unfortunately.

**Comment by dbuezas** [comment]
> Can you share what exactly you did to resolve it 

I also had a similar issue and I fixed it by disconnecting, unpairing and then repairing (via bluetoothctl, check out pairing in the docs)

**Comment by FPMilan** [comment]
That I also tried but without success. I then updated the firmware of my eq3 to 1.46 but now the device is not displaying the pairing code when requested from bluetoothctl. What firmware version are you running?

**Comment by andrei-micu-ro** [comment]
- Terminal - bluetoothctl - remove device
- (Optional) Pull out batteries, put them back in - configure date/time
- bluetoothctl - pair device - when it asks for pin keep the valve wheel pressed for 3 sec, punch in pin 

You should be set

**Comment by FPMilan** [comment]
<img width="406" alt="image" src="https://user-images.githubusercontent.com/10432654/200114999-6afee1f2-de73-43d7-b1d3-9dd2cbb8d51e.png">
and 
<img width="746" alt="image" src="https://user-images.githubusercontent.com/10432654/200115033-a8860ade-0d15-4056-83f9-9c94b99a943b.png">

thanks for the hint with the valve wheel for pairing @andrei-micu-ro 
but still it will not report in Home Assistant. 
Would you tell me where you found the connection logs?

**Comment by andrei-micu-ro** [comment]
Strange, it's connected, so it should pass through to HA
Do you have other BT devices working with HA already ?
If so you can just give it 1 hour - it should send some signals.
If this is the first BT device in HA then maybe the problem is different and not linked to this integration.

Do you run HassIo or HA in docker ? For docker you need a few permissions so that HA pod sees the bus and be able to access BT
You can try adding the BLE tracker in HA (look for the BLE integration) and check whether other BT signals reach HA (phone, a watch, a BT toothbrush, etc) to ensure HA is properly configured

**Comment by dbuezas** [comment]
Do you have an EspHome BTProxy? If you do, HA will try to use that and that's broken at the moment

**Comment by FPMilan** [comment]
> 

Yes, very good gues @dbuezas  I do have an EspHome running, which is for connecting to BLE devices, didn't realize this might affect the main bluetooth, will do some reading on how this can be resolved. Thanks.

(And for completion, I am running Home Assistant Core on Home Assistant OS on a RPi 3+)

**Comment by dbuezas** [comment]
BTW, to get more logs, add this to your `configuration.yaml`:
```yaml
logger:
  default: warning
  logs:
    custom_components.dbuezas_eq3btsmart: debug
```
You'll get more detail on the intermediate states, and you will see also if the BTHome is discovering the Thermostat.

**Comment by FPMilan** [comment]
Just plugged in another bluetooth dongle to my RPi and I get flooded with devices wehn running bluetoothctl and the best thing is that now eq3 is working! (at least for one so far :))

**Comment by dbuezas** [comment]
If you are interested about the rssi (signal strength), you can find it in the entity attributes.
You can even plot it over time

![image](https://user-images.githubusercontent.com/777196/200141366-24289b48-5bc4-4b65-923c-c267c56ee08a.png)

More:
https://community.home-assistant.io/t/eq3-bt-smart-thermostat-working-with-v-2022-7/476620/6?u=mateine

**Comment by FPMilan** [comment]
very nice thanks for sharing!

**Comment by FPMilan** [comment]
Just one different question, are you aware of a way to use temperature from a different sensor?

**Comment by dbuezas** [comment]
There was a PR to do that (only show in ui) in the "official" integration" but HA rejected it.
I could add it if there's interest.
One thing you could do is checking the valve attribute: if it is >0, the temp is lower than target

**Comment by FPMilan** [comment]
That would be great if you can share it. Do you know why it got rejected?

07.11.2022 08:05:49 David Buezas ***@***.***>:

**Comment by dbuezas** [comment]
https://github.com/home-assistant/core/pull/50763

I could add it, this is a custom component so wild west

**Comment by dbuezas** [comment]
https://github.com/home-assistant/core/pull/50763

I could add it, this is a custom component so wild west

**Comment by dbuezas** [comment]
> Do you know why it got rejected?

Not in line with the architecture. Makes sense actually

**Comment by FPMilan** [comment]
do you have it running yourself? (the secondary thermometer) 
and I have another question, you have the service eq3 fetch schedule, get serial and set schedule, how can I run the service and then see/disply the results? plus could you give an example also of how to set a new schedule?

**Comment by dbuezas** [comment]
would you open a new issue for this?
It will be easier for others to find it later :)
