### ISSUE TITLE
After update to 1.0.3 thermostats unavailable 

### ISSUE THREAD

**Issue by ChrisKolan** [dbuezas/eq3btsmart#21]
After the last update to 1.0.3 version from 1.0.0 my thermostats became unavailable. My logs show multiple warnings:

"Logger: homeassistant.components.climate
Source: runner.py:119
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 20:11:07 (3 occurrences)
Last logged: 20:11:07

Setup of climate platform dbuezas_eq3btsmart is taking over 10 seconds."

"Logger: homeassistant.bootstrap
Source: bootstrap.py:441
First occurred: 20:11:40 (8 occurrences)
Last logged: 20:18:42

Waiting on integrations to complete setup: climate.dbuezas_eq3btsmart, climate.dbuezas_eq3btsmart_2, climate.dbuezas_eq3btsmart_3"

"Logger: custom_components.dbuezas_eq3btsmart.python_eq3bt.eq3bt.bleakconnection
Source: custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py:121
Integration: dbuezas EQ3 Bluetooth Smart Thermostats
First occurred: 20:12:32 (15 occurrences)
Last logged: 20:19:04

[Thermostat living room] Broken connection [retry 1/10]:
[Thermostat bathroom] Broken connection [retry 1/10]:
[Thermostat bedroom] Broken connection [retry 1/10]:"

"Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:430
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 20:19:17 (3 occurrences)
Last logged: 20:19:17

Timed out adding entities for domain climate with platform dbuezas_eq3btsmart after 500s"

And one error:

"Logger: homeassistant
Source: helpers/entity.py:520
First occurred: 20:11:11 (18 occurrences)
Last logged: 20:19:17

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 520, in async_update_ha_state
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Thermostat bedroom"

**Comment by dbuezas** [comment]
Try v2.0.0, this issue should be solved.
But please reopen if the issue persist :)
