### ISSUE TITLE
One thermostat didn’t create additional sensors after update 

### ISSUE THREAD

**Issue by wjarka** [dbuezas/eq3btsmart#26]
I think it was 3.0 introducing the extra entities / sensors for each thermostat. It happened for three out of four thermostats. How do I force it for the fourth? Just delete EQ3 entity?

**Comment by wjarka** [comment]
Oh never mind. It did create them but the naming is off. For every thermostat I used the naming convention of “EQ3 room name”. This thermostat was the same but all the sensors are called “room name sensor name” for some reason. The other ones followed my convention and were called “EQ3 room name sensor name”

**Comment by dbuezas** [comment]
That's really weird, deleting and re-adding should make all names match again
