### ISSUE TITLE
Broken connection issue in log

### ISSUE THREAD

**Issue by michapr** [dbuezas/eq3btsmart#27]
Hi,

thank you for this integration!

It looks like it is working fine, but I have many errors in log like these:
```
[A-Zimmer] Broken connection [retry 1/14]: [org.bluez.Error.NotPermitted] Not paired
[A-Zimmer] Broken connection [retry 1/14]: A-Zimmer - 00:1A:22:08:BF:D6: Failed to connect: [org.bluez.Error.Failed] Software caused connection abort
[A-Zimmer] Broken connection [retry 2/14]: [org.bluez.Error.NotPermitted] Not paired
[A-Zimmer] Broken connection [retry 2/14]: A-Zimmer - 00:1A:22:08:BF:D6: Failed to connect: [org.bluez.Error.Failed] Software caused connection abort
[A-Zimmer] Broken connection [retry 3/14]: [org.bluez.Error.NotPermitted] Not paired
```
most only "1/14" , sometimes 2/14 and 3/14.

Is this "normal", or what can I do? Setting temperature is working fine...

Thanks!

**Comment by dbuezas** [comment]
Do you have multiple bluetooth adapters, or BTProxy?

**Comment by michapr** [comment]
no,...
```
hciconfig
hci0:   Type: Primary  Bus: USB
        BD Address: 00:1A:7D:DA:71:0F  ACL MTU: 310:10  SCO MTU: 64:8
        UP RUNNING
        RX bytes:306470108 acl:15326 sco:0 events:9586488 errors:0
        TX bytes:913306 acl:14047 sco:0 commands:95964 errors:0
```

But have enabled the adapter in HA integrations- maybe this is the reason?

**Comment by dbuezas** [comment]
Maybe that's the case, you could try disabling them temporarily to confirm that. I added retries because I was having reliability issues with one of my adapters, but that specific error is nee to me.

**Comment by michapr** [comment]
I have disabled - connection error at all.
Then have removed the Bluetooth integration - other error, and is not working more.
```
[A-Zimmer] Broken connection [retry 1/14]: A-Zimmer - 00:1A:22:08:BF:D6: Failed to connect: No backend with an available connection slot that can reach address 00:1A:22:08:BF:D6 was found: The proxy/adapter is out of connection slots; Add additional proxies near this device
[A-Zimmer] Broken connection [retry 2/14]: A-Zimmer - 00:1A:22:08:BF:D6: Failed to connect: No backend with an available connection slot that can reach address 00:1A:22:08:BF:D6 was found: The proxy/adapter is out of connection slots; Add additional proxies near this device
[A-Zimmer] Broken connection [retry 3/14]: A-Zimmer - 00:1A:22:08:BF:D6: Failed to connect: No backend with an available connection slot that can reach address 00:1A:22:08:BF:D6 was found: The proxy/adapter is out of connection slots; Add additional proxies near this device
```

What is your configuration? 
I use 2022.12 (docker installation) and external (USB) Bluetooth adapter.
Your Bluetooth adapter is enabled in integration?

Thanks!

**Comment by dbuezas** [comment]
Ohhh, you mean the Bluetooth component, I thought you meant other Integrations that were Bluetooth based.
This repo uses and needs the Bluetooth component.

I use HA OS on an ODroid N2+ (aka home assistant blue)

I assume you have paired the devices successfully before, since you say they work.

In this case, although I haven't seen that particular error, I'd say it is "normal". Not good, but Bluetooth seems to be kind of unstable still, depending a lot on the Bluetooth chipset.

Just out of curiosity, what Bluetooth adapter and chipset, and how many thermostats do you use?

**Comment by LXR85** [comment]
I have a similar issue on my Raspberry Pi 3B+ using the built-in Bluetooth adapter. All 4 thermostats work fine for a week or so and then 2 of them randomly disconnect and are not available anymore in Home Assistant:

![image](https://user-images.githubusercontent.com/6502056/207674193-f0c8f7ed-6456-4ae4-8cf0-6157d4c807cd.png)

Removing them in “bluetoothctl” and then pairing them again fixes the issue temporarily.

**Comment by michapr** [comment]
@LXR85 - would be interesting if you could show the related logs for this "go offline" issue.

**Comment by michapr** [comment]
> Just out of curiosity, what Bluetooth adapter and chipset, and how many thermostats do you use?

BTW: I'm using Pi4, have disabled the internal USB adapter because it had many (known) problems - nearly same as for Pi3B+ ...
Was using it before with HA and eq3lib based on bluepy - must say without problems...

USB-adapter:
```
 ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
  idVendor           0x0a12 Cambridge Silicon Radio, Ltd
  idProduct          0x0001 Bluetooth Dongle (HCI mode)
  iProduct                2 CSR8510 A10
``` 

Have not paired, is not needed for Firmware 1.20 (and does not work - org.bluez.Error.AuthenticationCanceled ).

And - I just have seen every 5 minutes this errors in syslog:
```
Dec 14 20:15:29 raspberrypi kernel: [262230.968128] Bluetooth: hci0: security requested but not available
Dec 14 20:15:30 raspberrypi kernel: [262231.468773] Bluetooth: hci0: security requested but not available
```
I use only one Bluetooth thermostat near the gateway, all the others in my home are Z-Wave based.
Was looking for alternate solution and out of technical interest ;)

**Comment by michapr** [comment]
Good news.
After hci0 reset these messages will not come more.
I have now some error messages, but this seems to be ok for Bluetooth connections.
```
2022-12-15 09:23:31.640 WARNING (MainThread) [custom_components.dbuezas_eq3btsmart.python_eq3bt.eq3bt.bleakconnection] [A-Zimmer] Broken connection [retry 1/14]: A-Zimmer - 00:1A:22:08:BF:D6: Failed to connect: [org.bluez.Error.Failed] Software caused connection abort
2022-12-15 09:28:30.564 WARNING (MainThread) [custom_components.dbuezas_eq3btsmart.python_eq3bt.eq3bt.bleakconnection] [A-Zimmer] Broken connection [retry 1/14]: A-Zimmer - 00:1A:22:08:BF:D6: Failed to connect: [org.bluez.Error.Failed] Software caused connection abort
2022-12-15 10:28:30.140 WARNING (MainThread) [custom_components.dbuezas_eq3btsmart.python_eq3bt.eq3bt.bleakconnection] [A-Zimmer] Broken connection [retry 1/14]: A-Zimmer - 00:1A:22:08:BF:D6: Failed to connect: [org.bluez.Error.Failed] Software caused connection abort
```
So my issue could be closed.

Not sure how about the other issue of @LXR85 , is a problem if mixed issues ... ;)
I would suggest to make a new one with the right topic @LXR85 - what do you think?

Thanks!

**Comment by dbuezas** [comment]
Yes, that's unfortunately normal. Thanks for the report!
