### ISSUE TITLE
'BluetoothManager' object has no attribute 'async_get_discovered_devices_and_advertisement_data_by_address'

### ISSUE THREAD

**Issue by andrei-micu-ro** [dbuezas/eq3btsmart#31]
![image](https://user-images.githubusercontent.com/73104962/210743786-8801668e-5fdb-4811-8217-166b387e4ac9.png)
I keep getting this error after the latest HA update (2023.1) and thermostats not connecting.

**Comment by dbuezas** [comment]
I haven't installed the last version yet, but I'll fix it soon. This is related a hack I had to implement for multiple bt adapters, which I read should now be solved by HA itself.

In the meanwhile, try changing the Bluetooth adapter to "Auto" in the device config (see https://github.com/dbuezas/eq3btsmart#device-options)

**Comment by andrei-micu-ro** [comment]
Worked like a charm, thanks. You can close it once you fix the underlying issue.

**Comment by dbuezas** [comment]
Fixed in v4.0.1
