### ISSUE TITLE
Can't pair eq3

### ISSUE THREAD

**Issue by thkaiser** [dbuezas/eq3btsmart#33]
Hi,

I still have a lot of problems with the eq3 valves with pairing.
With the original version eq3btsmart it still works without pairing.
Is there an option to use the module without pairing?

**Comment by dbuezas** [comment]
What do you mean that it works with the original version?  I think the original one doesn't work at all in newer HA versions (after 2022.7 IIRC)

Did you pair through bluetoothctl?
Do you have an EspHome Btproxy by any chance?

**Comment by thkaiser** [comment]
Sorry for the misunderstanding, it worked with 2022.7.7 and I tried to upgrade to an actual version without success.
I tried to pair via bluetoothctl and after entering the pin, there is an authentication failed message.
I don't have an Btproxy.
I also use the calor BT App on the phone, which already paired the valves.

**Comment by dbuezas** [comment]
Ohh, gotcha. Which firmware version?
Note that if you pair them with your phone, they may stop being able to talk to the adapter in HA. I haven't tried it myself, but read that they need to be repaired

**Comment by thkaiser** [comment]
I use version 1.46, I haven't found a way to pair again, at least not with power off. Probably a full reset could help, but then I need to program everything again.

**Comment by dbuezas** [comment]
Just long press the center wheel until it says pair.
Regarding programming, with this integration you can extract it and change it via a service in a reasonably convenient manner (if you ever need to do it again).

**Comment by thkaiser** [comment]
Hi David,

I was trying this all the time and it still don't work on my raspberry pi3. I started another installation on an ordinary notebook. There it works now. So there may be a problem in the environment of the raspberry pi3. 
Thanks for your help.

**Comment by dbuezas** [comment]
Oh, ok, thanks for getting back with the information. I don't see why it shouldn't work on a pi, but I don't own one yo test it. Maybe it was a bad integration setup as with the other issue I recently closed (deleting and re-adding the device fixed it).

**Comment by thkaiser** [comment]
Hi David, I was able to dig a bit more into it. It looks like, that this occurs in an situation with multiple bluetooth adapters. I paired all eq3 devices with hci1 (internal pi3), but it looks like that, even with the settings org/bluez/hci1 the error message is "not paired" or "not found". With bluetoothctl I get a correct list of paired-devices. Any idea how this should work?
Regards Thomas

**Comment by dbuezas** [comment]
Mmmm, I don't know that much about bluetooth and pairing to be honest, but my guess is that one of these hold:
* Some devices are too far away and communication is too unstable
* Something went wrong with the pairing and the wrong adaptor ended up pairing
* Bleak somehow deals differently with the rpi adapter (I make a call to bledevice.pair() just in case, which just returns true if already paired with my adapters). You could try removing that line (search for ".pair")
* You are using a different way to install HA (e.g docker) than me, and the BT adapter is not accessible somehow
* You didn't setup the bluetooth adapter integration in HA
* You have more than 3-5 EQ3, and the adapter can't connect with all of them at the same time (disable persistant conection in the EQ3 integartion configuration options in the integrations panel)

Have you tried the Auto and Local Only modes? the "local only" does round robin across the adapters so if you have 2, this may end up finding the right one.

If none of the suggestions gets you anywhere, then please enable debug mode and debug logs and post some relevant logs here.

To enable logging, add this to your `configuration.yaml`
```yaml
logger:
  logs:
    custom_components.dbuezas_eq3btsmart: debug
    bleak_retry_connector: debug
```
