### ISSUE TITLE
no ignore option for discovered devices on integrations page

### ISSUE THREAD

**Issue by renarena** [dbuezas/eq3btsmart#34]
as said in the title :-)

**Comment by dbuezas** [comment]
I see, thanks for the issue.

Note to self:
* https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#unique-ids
* I think [this](https://github.com/dbuezas/eq3btsmart/blob/3451599735b2a3da3088d5d7aff186f5321df542/custom_components/dbuezas_eq3btsmart/config_flow.py#L105) should go on line 90

**Comment by dbuezas** [comment]
As a quick fix (in case you haven't realised yourself) you can add it and disable it. I'll try to fix it the next time I make a release
I guess this should definitely be fixed before attempting to merge into Home Assistant's core.
