### ISSUE TITLE
Error updating: Characteristic d0e8434d-cd29-0996-af41-6c90f4e0eb2a not found!

### ISSUE THREAD

**Issue by bvweerd** [dbuezas/eq3btsmart#43]
Hi,

Yesterday I had numerous errors with the TRVs at v1.20. After updating I am left with just a few annoying errors, one is:

Error updating: Characteristic d0e8434d-cd29-0996-af41-6c90f4e0eb2a not found!

`2023-01-28 12:17:18.175 DEBUG (MainThread) [custom_components.dbuezas_eq3btsmart.python_eq3bt.eq3bt.bleakconnection] [TRV_Hal] Connected
2023-01-28 12:17:18.185 DEBUG (MainThread) [custom_components.dbuezas_eq3btsmart.python_eq3bt.eq3bt.bleakconnection] [TRV_Hal] Paired: True 
2023-01-28 12:17:20.385 DEBUG (MainThread) [custom_components.dbuezas_eq3btsmart.python_eq3bt.eq3bt.bleakconnection] [TRV_Hal] Broken connection [retry 2/14]: Characteristic d0e8434d-cd29-0996-af41-6c90f4e0eb2a not found!
Traceback (most recent call last):
  File "/config/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py", line 190, in _async_make_request_try
    await conn.start_notify(PROP_NTFY_UUID, self.on_notification)
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 639, in start_notify
    raise BleakError(f"Characteristic {char_specifier} not found!")
bleak.exc.BleakError: Characteristic d0e8434d-cd29-0996-af41-6c90f4e0eb2a not found!
`

TRV is at v1.46
HA 2023.1.7
eq3btsmart 5.0.1

I'm using a USB BTdongle + 1 esp proxy, but for this TRV the proxy is out of range.
 
In the cl tool bluetoothctl I can see at least all TRV info and connection status

What and how can I provide or test what the root cause is?

**Comment by dbuezas** [comment]
Let's dig deeper:
* Have you tried restarting HA and even rebooting the device? (I had to do it once to revive the Bluetooth adapter stack)
* Do you get some updates in spite of the error?
* What options do you have selected in the device options panel? (Devices -> eq3device -> options) (screenshot is best)
* Have you tried forcing the hci0 Bluetooth adapter there? Or the "only locals" one.

**Comment by dbuezas** [comment]
A test you can also do is reverting to the older version and retest. With this we can make sure it is version dependent and not a coincidence

**Comment by bvweerd** [comment]
Changing to v1.20 did not change the behavior.

What changed the behavior is moving the TRV physically in range of the proxy and out of the range of the USB Bluetooth adapter (CBT40NANO). This caused immediate response of the TRV without the above error.

So it seems I have to look in the behavior of the USB Bluetooth module. Unfortunately that's the only one I have lying around right now...

**Comment by dbuezas** [comment]
I mean the version of this integration, not the firmware of the TRV

**Comment by bvweerd** [comment]
> I mean the version of this integration, not the firmware of the TRV

A, I could have known :-)

5.0.0 and 4.0.1 have the same behavior

**Comment by dbuezas** [comment]
Ok, then it is a bluetooth adapter issue. We can still chat here but I'll close the issue to avoid confusion.

What chipset does your adapter have?
Did you see the analysis done here? https://www.home-assistant.io/integrations/bluetooth/

**Comment by bvweerd** [comment]
Thanks so far!

I see I'm running 5.53 of Bluez, so let me try to build the 5.63 or later first

**Comment by bvweerd** [comment]
Doesn't help to update Bluez.

Another experiment with another TRV, set to local only. No errors at all. Seems to be really the one buggy TRV only.

**Comment by dbuezas** [comment]
How annoying... Have you tried manually pairing through bluetoothctl? (I know it doesn't need a pin, but still). You could also try factory resetting it or updating its firmware with the Calor app. Wish you luck!

**Comment by dbuezas** [comment]
And what adapter chipset is it? note that the link I sent you mentions that some don't work well 🤷

**Comment by bvweerd** [comment]
How...

I upgraded, downgraded and upgrade the firmware of the TRV, no changes. Now I did a factory reset from the menu of the TRV, and... magic! Apparently that did the trick.

Thanks for listening to me and thinking along. And thanks for the great effort in creating this integration!

**Comment by dbuezas** [comment]
🎉 happy to hear!
Sure, it's fun and I learn a lot from all the different issues people have :)
