### ISSUE TITLE
BT Proxy

### ISSUE THREAD

**Issue by maciekelga** [dbuezas/eq3btsmart#44]
Hi,

I see there is finally running functionality of BT Proxy. Is it working via Shelly Gen2 devices? I have Shelly Plus 1 PM which can work as a proxy for BT. Is it any way to pair Eq3 BLE with Shelly?

**Comment by dbuezas** [comment]
Hi there!
As far as I know the Shellys can only act as passive proxies (no connection), and this TRV unfortunately requires active connections. 
Except if you flash EspHome in them of course,
