### ISSUE TITLE
Is it possible to set this up without a bluetooth adaptor and rely solely on ESP BT Proxies

### ISSUE THREAD

**Issue by privatesam** [dbuezas/eq3btsmart#47]
My Home Assistant instance runs inside a virtual machine on my server so it doesn't have access to a bluetooth adaptor directly.  I do however have a load of ESP32 kicking around so I was wondering whether it was possible to use this integration with the bluetooth proxies I've been reading about on another issue thread for this repo? 

Thanks in advance.

**Comment by dbuezas** [comment]
TL;DR: Yes it works.

Some report some instabilities on the long run, but it is not known if they are a power supply issue, old thermostat firmware versions, etc.
Go for it! :)

**Comment by privatesam** [comment]
Yep!  Working very nicely!  Got 10 valves and about 5 proxies.  2 valves are refusing to show up even after manually entering them but I'm going to reset and fiddle with them later.  Thanks so much for this integration its so slick.  I'd been wrestling with tasmota and their eq3 implementation but it was a real headache to troubleshoot and integrate nicely into HA - you've done the hardwork so thank you!!!
