### ISSUE TITLE
What does "Fetch Schedule" actually do?

### ISSUE THREAD

**Issue by privatesam** [dbuezas/eq3btsmart#51]
Does the "Fetch Schedule" button actually pull the current schedule from the valve and if so how and where does it store it in Home Assistant?

**Comment by dbuezas** [comment]
See here: https://github.com/dbuezas/eq3btsmart#viewing-schedules

**Comment by privatesam** [comment]
Ooops!  My bad.

**Comment by dbuezas** [comment]
No problem :)
I use this quite a bit to change the schedules so it's well tested. 
Feel free to ask if you have any issues setting it with the service. If you have multiple schedules you want to change back and forth, you can make a script in the automations section of HomeAssistant that calls the service with predefined schedules
Happy to hear from someone else using it too!
