### ISSUE TITLE
BT Proxy: ESPHomeClient' object has no attribute '_device_path'

### ISSUE THREAD

**Issue by wjarka** [dbuezas/eq3btsmart#52]
This is showing up in the logs all the time when using BTProxy only

> This error originated from a custom integration.
> 
> Logger: homeassistant
> Source: custom_components/dbuezas_eq3btsmart/sensor.py:178 
> Integration: eQ-3 Bluetooth Smart Thermostats (dbuezas) (documentation, issues) 
> First occurred: 12:19:02 PM (1122 occurrences) 
> Last logged: 4:08:11 PM
> 
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_update_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 607, in _async_write_ha_state
>     state = self._stringify_state(available)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _stringify_state
>     if (state := self.state) is None:
>   File "/config/custom_components/dbuezas_eq3btsmart/sensor.py", line 178, in state
>     return self._thermostat._conn._conn._backend._device_path
> AttributeError: 'ESPHomeClient' object has no attribute '_device_path'
>

**Comment by dbuezas** [comment]
Do you have the debug entities enabled?
I made those before the BTProxy worked, so it could be that something crashes in them with BTProxies.
I think we can merge this ticket with #53

**Comment by wjarka** [comment]
I commented in the other one. I had debug entities enabled for two TRVs. Disabled them and will see if anything shows up in the logs during the night. Will update in the morning.

thanks!

**Comment by dbuezas** [comment]
Thank you, I should start using a BTProxy, but I ended up buying top class long range bluetooth dongles so I have good range w/o BTProxies so I'm a bit hesitant to spend time on that instead of my [other](https://github.com/dbuezas/lovelace-plotly-graph-card) HA project 😁

**Comment by wjarka** [comment]
Logs clear with debug entities disabled ;)

**Comment by wjarka** [comment]
My goal was to move the Pi somewhere else and “somewhere else” might not work even with the best long range dongles :))

**Comment by dbuezas** [comment]
Right, yes. That's the beauty of BTProxies, right?
I'll setup one at least for testing (the things I do for a github star 🤣). I've unfortunately used esp8266 for all my esphome home made gadgets, so it will have to be a dedicated one.

**Comment by wjarka** [comment]
Definitely! Especially with something as small as M5Stack Atom Lite.

**Comment by wjarka** [comment]
I think this one can be closed, btw ;)

**Comment by orgebar** [comment]
The messages still appear, when debugging is enabled. Is this ok? Is this an issue at all or just due to the fact that in comparison with bt-dongles for bt proxy there is no device path that can be shown in the device path entity?

**Comment by dbuezas** [comment]
Yes, most likely due to the btproxys. It doesn't affect functionality, only that entity will be unavailable, so it ok
