### ISSUE TITLE
Log cleanup: Pairing not available

### ISSUE THREAD

**Issue by wjarka** [dbuezas/eq3btsmart#54]
There is a lot of those in the logs. Since we are not using pairing to use proxy - can this be removed?

> This error originated from a custom integration.
> 
> Logger: custom_components.dbuezas_eq3btsmart.python_eq3bt.eq3bt.bleakconnection
> Source: custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py:174 
> Integration: eQ-3 Bluetooth Smart Thermostats (dbuezas) (documentation, issues) 
> First occurred: 12:18:59 PM (864 occurrences) 
> Last logged: 4:08:23 PM
> 
> [Sypialnia] Failed paring: Pairing is not available in ESPHome.
> [EQ3 Gabinet] Failed paring: Pairing is not available in ESPHome.
> [EQ3 Rurkowy] Failed paring: Pairing is not available in ESPHome.
> [EQ3 Gościnny] Failed paring: Pairing is not available in ESPHome.
>

**Comment by dbuezas** [comment]
https://github.com/dbuezas/eq3btsmart/releases/tag/v5.0.3-beta
Try this version (see [here](https://hacs.xyz/docs/faq/beta/) to enable beta versions). If it works well I'll release a production version

**Comment by wjarka** [comment]
Downloaded. Will update you in the morning if it works and if the logs are gone ;)

**Comment by wjarka** [comment]
Those seem to be gone as well in the beta version. No apparent issues so far. I think we can close this one ;)

**Comment by dbuezas** [comment]
Oh, cool, I'll release it then
