### ISSUE TITLE
Integration does not appear in Home Assistant

### ISSUE THREAD

**Issue by FPMilan** [dbuezas/eq3btsmart#6]
Just installed it via HACS, and also confirmed /config/custom_components/dbuezas_eq3btsmart/ is in place, yet home assistant is not detecting a new integration and also searching for it gives no results. 
Am I doing something wrong?
Thanks for any tips

**Comment by dbuezas** [comment]
Did you restart Home Assistant?

**Comment by FPMilan** [comment]
Yes, and after waiting for the night I can see a new entry when I click on add integration but adding it will give me this:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/10432654/196892184-06f8dbae-6f2c-4caa-b2a9-e413fc69dae8.png">

**Comment by dbuezas** [comment]
That's odd...
What do you see in the logs?
Last resort is deleting it, restarting, installing it and then restarting again.

**Comment by FPMilan** [comment]
Works now! 
Have updated Home Assistant Core to latest version.
Sorry should have done that at start.
Thanks for your responses anyway!
