### ISSUE TITLE
can't set a schedule

### ISSUE THREAD

**Issue by fettesb** [dbuezas/eq3btsmart#62]
I can't set a schedule on my CC-RT-BLE-EQ from eQ-3 AG
EQ3 Firmware: 146
Home Assistant 2023.4.2

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:225
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:44:41 (2 occurrences)
Last logged: 14:48:21

[2786438208] Error handling message: required key not provided @ data['days']. Got None required key not provided @ data['target_temp_0']. Got None (invalid_format) Sascha from 192.168.178.28 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15)
[2800145768] Error handling message: required key not provided @ data['days']. Got None required key not provided @ data['target_temp_0']. Got None (invalid_format) Sascha from 192.168.178.28 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36)

################################################################################################

Logger: homeassistant.helpers.service
Source: helpers/service.py:553 
First occurred: 14:43:46 (1 occurrences) 
Last logged: 14:43:46

Unable to parse services.yaml for the dbuezas_eq3btsmart integration

################################################################################################

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:410 
First occurred: 14:44:41 (2 occurrences) 
Last logged: 14:48:21

websocket_api script: Error executing script. Invalid data for call_service at pos 1: required key not provided @ data['days']

**Comment by dbuezas** [comment]
Please share the yaml you are passing. Or is this related to the latest home assistant version?

**Comment by dbuezas** [comment]
Oh yes the UI is gone, it should look like this:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/777196/231224334-11b75e06-abb8-4009-828a-7cc586153cd7.png">

It seems like it broke with 2023.4, I'll fix ot later then, thanks for reporting!

**Comment by dbuezas** [comment]
Ok, i'm quite sure this is a bug in HA, but removing the descriptions from the services seems to fix it. I may re-add them later if this gets fixed.
Please try v6.1.2 and reopen if this didn't fix it for you.

**Comment by fettesb** [comment]
now v6.1.2 shows all settings but when I press CALL Service followed by the green check mark. And in the HA Log comes...


Logger: homeassistant.helpers.service
Source: helpers/service.py:757 
First occurred: 23:05:52 (1 occurrences) 
Last logged: 23:05:52

Unable to find referenced entities climate.kuche or it is/they are currently not available

I can control my eq3 so it must be available right?
when I press fetch schedule I get the right settings what I configured as my schedule

**Comment by fettesb** [comment]
now it is working. Thank you once again

**Comment by dbuezas** [comment]
I'll add that detail in the readme
