### ISSUE TITLE
No thermostats after Core Update Online

### ISSUE THREAD

**Issue by olikri** [dbuezas/eq3btsmart#64]
Since the last update to the new core version, my thermostats are no longer visible or are shown as inactive

The following error messages are given to me according to the log

    Error setting up entry Bad for dbuezas_eq3btsmart
    Error setting up entry Wohnzimmer for dbuezas_eq3btsmart
    Error setting up entry Schlafzimmer for dbuezas_eq3btsmart
    Error setting up entry Küche for dbuezas_eq3btsmart

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/dbuezas_eq3btsmart/__init__.py", line 39, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by dbuezas** [comment]
That's odd. Mine also had a hiccup, and did use to work better, but they do still run.
Does a reboot change anything?

**Comment by dbuezas** [comment]
Are you using btproxy? I think something is going wrong there

**Comment by olikri** [comment]
Unfortunately, restarting doesn't change anything.
The system is also set up directly without a container. I don't use BTProxy either

**Comment by dbuezas** [comment]
I will try this
https://github.com/StephanJoubert/home_assistant_solarman/commit/0cd2e8d0f98133682522a7e622e29373b5410227

**Comment by dbuezas** [comment]
It looks like that method was deprecated 
https://community.home-assistant.io/t/issues-with-nest-protect-after-installing-20230503-1/567537/5

**Comment by dbuezas** [comment]
What version are you using? It looks like I already did this a long way back
https://github.com/dbuezas/eq3btsmart/blob/e3624e4d65052bfa5700bd08090ba1c67f40c589/custom_components/dbuezas_eq3btsmart/__init__.py#L55

**Comment by olikri** [comment]
Ok I saw that the error is 18 inches in front of the screen.
After updating the integration to the latest I can see the thermostats again.
I definitely have to keep everything up to date, then such errors will not appear again

**Comment by olikri** [comment]
Thank you anyway for your quick help and answers to the problem.
You are one of the few who take care of problems and try to help as soon as possible.
Please keep it up and I am very happy to be able to use your software

**Comment by dbuezas** [comment]
No problem, it happens :)
