### ISSUE TITLE
BLEDevide.rssi py.warning in Home Assistant log

### ISSUE THREAD

**Issue by maciekelga** [dbuezas/eq3btsmart#66]
Hi, today i discovered in my log following warning

![image](https://github.com/dbuezas/eq3btsmart/assets/65248075/9c9fafce-b6db-42e9-a493-7122e313a8aa)

**Comment by maciekelga** [comment]
@dbuezas should I do anything? I still get this warning.

**Comment by dbuezas** [comment]
Have you updated?

**Comment by dbuezas** [comment]
v6.2.1 just released now. The fix was missing in the previous one. Let me know if updating now solves it :)

**Comment by maciekelga** [comment]
Thanks, updated. I will let You know!

**Comment by maciekelga** [comment]
Fixed :)
