### ISSUE TITLE
Cannot add repo in HACS

### ISSUE THREAD

**Issue by berlund** [dbuezas/eq3btsmart#69]
On adding this integration in HACS as per instructions in the README, it says that the repo could not be found. Looks like a leading slash in the URL could be the problem?

<img width="491" alt="image" src="https://github.com/dbuezas/eq3btsmart/assets/19695638/c59ae780-1f27-4ee0-9331-8b4df13178f8">

Afterwards, the error "Repository David Buezas /https://github.com/dbuezas/eq3btsmart not found" is displayed.

**Comment by Nummer17** [comment]
Same problem here  but i see a leading backslash in URL:  /https://github.com/dbuezas/eq3btsmart not found.

**Comment by CMMenzel** [comment]
I am facing the same - "Repository David Buezas /https://github.com/dbuezas/eq3btsmart not found" whether I follow the link on GitHub or try to install from HACS search.

**Comment by EuleMitKeule** [comment]
You might have to add a `.git` at the end, so the link should be `https://github.com/dbuezas/eq3btsmart.git`. I am not 100% sure about this though.

**Comment by dbuezas** [comment]
Unfortunately adding the `.git` didn't work either

**Comment by EuleMitKeule** [comment]
I think I found the issue:
The `Owner` field in the link creator needs to be set to the GitHub username, and the `Repository` field needs to be the name of the repo on GitHub.
![grafik](https://github.com/dbuezas/eq3btsmart/assets/47421406/fafcf720-eb3c-4370-9650-ecafd83fd91e)
I will provide a PR with the updated link.
