### ISSUE TITLE
Missing integration icon

### ISSUE THREAD

**Issue by Kimotu** [dbuezas/eq3btsmart#73]
When listing integrations, there is no icon displayed left next to "eQ-3 Bluetooth Smart Thermostats (dbuezas)".

Examining the HTML source reveals an image linked to https://brands.home-assistant.io/dbuezas_eq3btsmart/icon.png which does not exist and returns 404.

Could you please readd the missing icon or fix the link so that it points to a valid icon?

Thanks.

**Comment by dbuezas** [comment]
AFAIK brands need to be added to the home assistant core repo so I can't do this in the code of this integration.
When I finish other projects I intend to get back to this one and make a PR to home assistant, so this will eventually be solved.

**Comment by EuleMitKeule** [comment]
Actually you should be able to simply commit to the [home-assistant brands repo](https://github.com/home-assistant/brands) for the logo to show up.

**Comment by dbuezas** [comment]
I'll eventually clean this up and make a PR to home assistant, where the brand already exists with another name

**Comment by EuleMitKeule** [comment]
This issue can and will only be fixed once the integration is being merged into `core`, so this issue technically is not regarding this repo and can be closed.
