### ISSUE TITLE
Target temperature should be displayed immediately

### ISSUE THREAD

**Issue by EuleMitKeule** [dbuezas/eq3btsmart#77]
The current behaviour of the target temperature is the following: When the user sets a new target temperature via the home assistant UI, the temperature is sent to the thermostat. The target temperature UI control immediately resets and will only change to the new temperature after the thermostat has sent its new state message. This leads to undesirable behaviour since the user expects the target temperature he sets to be then displayed, and the current temperature to display this temperature once the thermostat has applied it.

**Comment by dbuezas** [comment]
It's on purpose in case the connection doesn't succeed. 
You can configure what the current temperature shows, see https://github.com/dbuezas/eq3btsmart?tab=readme-ov-file#device-options

<img width="420" alt="208250665-9cead674-6ea3-4260-aa3f-a3237196934b" src="https://github.com/dbuezas/eq3btsmart/assets/777196/135f8b9a-ab86-40e3-9e1f-d52607c00325">
