### ISSUE TITLE
Unhandled exceptions in fetch serial task

### ISSUE THREAD

**Issue by EuleMitKeule** [dbuezas/eq3btsmart#84]
When the `FirmwareVersionSensor` fetches the serial number from the thermostat after Home Assistant started, the connection to the thermostat might fail and lead to a `TimeoutError` or similar exceptions. Since these errors are not handled or caught, an unhandled exception with a full stack trace will get logged. This is undesirable; exceptions that occur while fetching the serial should get logged and handled in a similar way to connection errors while updating in the `climate.async_scan` method.

**Comment by dbuezas** [comment]
Thanks!
