### ISSUE TITLE
Temp_celsius in HA Core 2025.1

### ISSUE THREAD

**Issue by maciekelga** [dbuezas/eq3btsmart#98]
Hi
In my HA logs i got following issue:

TEMP_CELSIUS was used from dbuezas_eq3btsmart, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/dbuezas/eq3btsmart/issues

**Comment by dbuezas** [comment]
Thanks! @EuleMitKeule is giving the integration a good revamp which includes fixing deprecations. We'll get there!

**Comment by EuleMitKeule** [comment]
This issue has already been fixed in `v6.3.0` and therefore this issue can be closed.

**Comment by maciekelga** [comment]
Confirm, it is fixed now, thank You😉
